language: swift
osx_image: xcode10.1

addons:
  homebrew:
    packages:
      - swiftlint

before_script:
  - swift package generate-xcodeproj --enable-code-coverage
script:
  - xcodebuild test -scheme CodableKit-Package
after_success:
  - bash <(curl -s https://codecov.io/bash)
